funquiz/urls.py
from django.contrib import admin
from django.urls import path, include
import game

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('game.urls', namespace='game'))
]

game/urls.py
from django.urls import path
from game import views

app_name='game'

urlpatterns = [
    # SERVER SIDE
    path('newgame', views.new_game, name='new_game'),
    path('newstage', views.start_new_game_stage, name='start_new_game_stage'),
    # CLIENT SIDE
    path('', views.index, name='index'),
    path('lobby', views.lobby, name='lobby'),
    path('listplayersingame', views.list_players_in_game, name='list_players_in_game'),
    path('allready', views.all_ready, name='all_ready'),
    path('isgamestarted', views.is_game_started, name='is_game_started'),
    path('cat', views.category_selection, name='category_selection'),
    path('q/<category_id>', views.question, name='question'),
]

game/models.py
from django.db import models
from random import randint, shuffle


class QuestionCategory(models.Model):
    name = models.CharField(max_length=256)

    @classmethod
    def get_random_categories(cls):
        ids = list(cls.objects.all().values_list('id', flat=True))
        shuffle(ids)
        ids = ids[0:4]
        categories = list(cls.objects.filter(id__in=ids).values('id', 'name'))
        shuffle(categories)
        return categories


class Question(models.Model):
    text = models.CharField(max_length=1024)
    category = models.ForeignKey(QuestionCategory, on_delete=models.CASCADE)

    @classmethod
    def get_random_question(cls, category_id):
        question_ids_in_cat = tuple(cls.objects.filter(category_id=category_id).values_list('id', flat=True))
        random_id = question_ids_in_cat[randint(0, len(question_ids_in_cat)-1)]
        output = {'id': '', 'category': '', 'text': '', 'answers': []}
        question = cls.objects.get(id=random_id)
        output['id'] = question.id
        output['category'] = question.category.name
        output['text'] = question.text
        answers = list(Answer.objects.filter(question_id=random_id).values_list('text', flat=True))
        shuffle(answers)
        output['answers'] = answers
        return output


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    text = models.CharField(max_length=1024)
    is_correct = models.BooleanField()


class Player(models.Model):
    name = models.CharField(max_length=32)


class Game(models.Model):
    code = models.CharField(max_length=16)
    is_started = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now=True)


class PlayersInGame(models.Model):
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    player = models.ForeignKey(Player, on_delete=models.CASCADE)


class GameStage(models.Model):
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    start_time = models.DateTimeField(auto_now=True)
    question = models.ForeignKey(Question, on_delete=models.CASCADE, blank=True, null=True)
    is_finished = models.BooleanField()
    
    @staticmethod
    def new(game):
        stage = GameStage.objects.create(game=game, is_finished=False)
        random_categories = QuestionCategory.get_random_categories()
        categories = []
        for random_category in random_categories:
            categories.append(GameStageCategories.objects.create(game_stage=stage, category_id=random_category['id']).category)
        return stage, categories
    
    def set_question(self, category:QuestionCategory):
        self.question = Question.get_random_question(category_id=category.id)
        self.save()
        return self.question

class GameStageCategories(models.Model):
    game_stage = models.ForeignKey(GameStage, on_delete=models.CASCADE)
    category = models.ForeignKey(QuestionCategory, on_delete=models.CASCADE)
    

class GameStageCategoryVoting(models.Model):
    game_stage = models.ForeignKey(GameStage, on_delete=models.CASCADE)
    player = models.ForeignKey(Player, on_delete=models.CASCADE)
    category = models.ForeignKey(QuestionCategory, on_delete=models.CASCADE)
    time = models.DateTimeField(auto_now=True)


class GameStageAnswers(models.Model):
    game_stage = models.ForeignKey(GameStage, on_delete=models.CASCADE)
    player = models.ForeignKey(Player, on_delete=models.CASCADE)
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE)
    time_taken = models.DecimalField(max_digits=8, decimal_places=4)
    time = models.DateTimeField(auto_now=True)

game/views.py
from django.shortcuts import render, HttpResponse
from django.http import JsonResponse
from .models import *
from random import randint, shuffle, choices
import string


# SERVER SIDE


def new_game(request):
    N = 6
    game_code = ''.join(choices(string.ascii_uppercase + string.digits, k=N))
    game = Game.objects.create(code=game_code)
    context = {'game_code': game_code}
    response = render(request, 'game/new_game.html', context=context)
    response.set_cookie('game_code', value=game_code)
    return response


def start_new_game_stage(request):
    game_code = request.GET['gameCode']
    game = Game.objects.get(code=game_code)
    stage, categories = GameStage.new(game=game)
    context = {
        "game_code": game_code,
        "stage_id": stage.id,
        "categories": categories
    }
    return render(request, 'game/server_category_selection.html', context)


# CLIENT SIDE


def index(request):
    context = {}
    return render(request, 'game/index.html', context=context)


def lobby(request):
    # check game exists
    try:
        game_code = request.GET['gameCode']
        game = Game.objects.get(code=game_code)
    except KeyError:
        return HttpResponse("Неправильный код игры")
    # get or create player
    player, created = Player.objects.get_or_create(name=request.GET['inputName'])
    # check user is in the game
    try:
        player_in_game = PlayersInGame.objects.get(game=game, player=player)
    except PlayersInGame.DoesNotExist:
        # check user is not in the game yet and don't let him in if the game is started
        if not game.is_started:
            player_in_game = PlayersInGame.objects.create(game=game, player=player)
        else:
            return HttpResponse("Простите, но игра уже началась...")

    context = {'player': player, 'game_code': game_code}
    response = render(request, 'game/lobby.html', context=context)
    response.set_cookie('player_id', value=player.id)
    response.set_cookie('game_code', value=game_code)
    return response


def list_players_in_game(request):
    try:
        game_code = request.COOKIES['game_code']
        players_in_game = list(PlayersInGame.objects.filter(game__code=game_code).values_list('player__name', flat=True))
        return JsonResponse({'status': 'ok', 'players': players_in_game})
    except Exception as exc:
        return JsonResponse({'status': 'error', 'error': str(exc)})


def all_ready(request):
    try:
        game_code = request.COOKIES['game_code']
        game = Game.objects.get(code=game_code)
        game.is_started = True
        game.save()
        return JsonResponse({'status': 'ok'})
    except Exception as exc:
        return JsonResponse({'status': 'err', 'error': str(exc)})


def is_game_started(request):
    try:
        game_code = request.COOKIES['game_code']
        game = Game.objects.get(code=game_code)
        return JsonResponse({'status': 'ok', 'is_started': game.is_started})
    except Exception as exc:
        return JsonResponse({'status': 'err', 'error': str(exc)})


def category_selection(request):
    try:
        game_code = request.COOKIES['game_code']
        stage = GameStage.objects.get(game__code=game_code, is_finished=False)
        categories = list(GameStageCategories.objects.filter(game_stage=stage).values_list('category__name', flat=True))
        context = {'status':'ok', 'ready': True, 'categories': categories}
    except GameStage.DoesNotExist:
        context = {'status': 'ok', 'ready': False }
    except Exception as exc:
        context = {'status': 'err', 'error': str(exc)}
    
    if request.is_ajax():
        return JsonResponse(context)
    else:
        return render(request, 'game/category_selection.html', context=context)


def question(request, category_id):
    q = Question.get_random_question(category_id=category_id)
    context = {'question': q}
    return render(request, 'game/question.html', context=context)

game/templates/game/category_selection.html
{%  extends 'base.html' %}
{% load i18n static %}

{% block content %}
    <div class="row">
      <div class="col-lg-12 text-center">
      {% if ready %}
        <h1 class="mt-5" id='title'>Выберите категорию вопроса</h1>
      {% else %}
        <h1 class="mt-5" id='title'>Ждем создание уровня</h1>
      {% endif %}
      </div>
      <div id="categories" class="col-lg-12">
        {% for category in categories %}
        <div class="col-lg-6 text-center">
          <button type="button" class="btn btn-primary btn-lg btn-block mt-5">{{category}}</button>
        </div>
        {% endfor %}
      </div>
    </div>
{% endblock %}

{% block js %}
<script>
  var checkStageTimer;
  function checkStage() {
    $.ajax({
      url:'{% url "game:category_selection" %}',
      success: function(data){
        if (data.status=='ok') {
          if (data.ready==true) {
            clearInterval(checkStageTimer)
            $('#title').text('Выберите категорию вопроса');
            $('#categories').innerHtml = '';
            data.categories.forEach(function(category){
                let catString = "<div class='col-lg-6 text-center'><button type='button' class='btn btn-primary btn-lg btn-block mt-5'>"+category+"</button></div>"
                $('#categories').append(catString);
            })
          }
        }
      }
    });
  }
  {% if not ready %}
  checkStageTimer = setInterval(checkStage, 1000);
  {% endif %}
</script>
{% endblock %}

game/templates/game/index.html
{%  extends 'base.html' %}
{% load i18n static %}

{% block content %}
<div class="row">
    <div class="col-lg-12 text-center">
        <h1 class="mt-5">Представьтесь, пожалуйста</h1>
    </div>
    <div class="col-lg-12 text-center">
        <form action="{% url 'game:lobby' %}" method="get">
            <div class="form-group mx-sm-3 mb-2">
                <input type="text" class="form-control" id="inputName" name="inputName" placeholder="Имя">
            </div>
            <div class="form-group mx-sm-3 mb-2">
                <input type="text" class="form-control" id="gameCode" name="gameCode" placeholder="Код игры">
            </div>
            <button type="submit" class="btn btn-primary btn-lg btn-block mt-5">Вперед!</button>
        </form>        
    </div>
</div>
{% endblock %}

game/templates/game/lobby.html
{%  extends 'base.html' %}
{% load i18n static %}

{% block content %}
<div class="row">
    <div class="col-lg-12 text-center">
        <h1 class="mt-5">Привет, {{ player.name }}</h1>
    </div>

    <div class="col-lg-12 text-center">
        <div class="form-group mx-sm-3 mb-2">
            Ждем других игроков...
        </div>
        <div id="readybutton">
            <button type="submit" class="btn btn-primary btn-lg btn-block mt-5" id='readybtn'>Все готовы!</button>
        </div>
    </div>

    <div class="col-lg-12 text-center">
        <div class="form-group mx-sm-3 mb-2">
            Уже в игре:
            <ul class="list-group list-group-horizontal" id='player_in_game'>
                {% for player_in_game in players_in_game %}
                <li class="list-group-item">{{player_in_game}}</li>
                {% endfor%}
            </ul>
        </div>
    </div>
    

</div>
{% endblock %}

{% block js %}
 <script type="text/javascript">
    function list_players_in_game() {
            $.ajax({
                method: "POST",
                url: "{% url 'game:list_players_in_game'%}", 
                data : {} 
            }).done(function (data) {
                if (data.status=='ok') {
                    $('#player_in_game').empty();
                    data.players.forEach(function(player_name){
                        $('#player_in_game').append('<li class="list-group-item">'+player_name+'</li>')
                    })
                } else {
                    alert(data.error);
                }
            })
        }
    list_players_in_game()
    let relist_players = setInterval(list_players_in_game, 5000);

    var gameStarted = false;
    function isGameStarted() {
            $.ajax({
                method: "POST",
                url: "{% url 'game:is_game_started' %}", 
                data : {} 
            }).done(function (data) {
                if (data.status=='ok') {
                    if(data.is_started == true) {
                        $('#readybtn').text('Погнали');
                        gameStarted = true;
                    }
                } else {
                    alert(data.error);
                }
            })
        }
    isGameStarted();
    let check_game = setInterval(isGameStarted, 5000);

    $('#readybtn').on('click', function(){
        if (gameStarted) {
            window.location.replace('{% url "game:category_selection" %}');
        } else {
            $.ajax({
                url: '{% url "game:all_ready" %}',
                success: function(data) {
                    if (data.status != 'ok') alert(data.error);
                }
            })
        }
    })
</script>
{% endblock %}

game/templates/game/new_game.html
{%  extends 'base.html' %}
{% load i18n static %}

{% block content %}
    <div class="row">
      <div class="col-lg-12 text-center">
        <h1 class="mt-5">Введите на вашем игровом устройстве код игры:<br>{{game_code}}</h1>
      </div>
    </div>
{% endblock %}

{% block js %}
<script>
function isGameStarted() {
            $.ajax({
                method: "POST",
                url: "{% url 'game:is_game_started' %}", 
                data : {game_code: '{{ game_code }}'} 
            }).done(function (data) {
                if (data.status=='ok') {
                    if (data.is_started == true) {
                        window.location.replace("{% url 'game:start_new_game_stage' %}?gameCode={{game_code}}")
                    } 
                } else {
                    alert(data.error);
                }
            })
        }
    let check_game = setInterval(isGameStarted, 5000);
</script>
{% endblock %}

game/templates/game/question.html
{%  extends 'base.html' %}
{% load i18n static %}

{% block content %}
    <div class="row">
      <div class="col-lg-12 text-center">
        <h1 class="mt-5">{{question.text}}</h1>
      </div>
      {% for answer in question.answers %}
      <div class="col-lg-6 text-center">
        <button type="button" class="btn btn-primary btn-lg btn-block mt-5">{{answer}}</button>
      </div>
      {% endfor %}
    </div>
{% endblock %}

game/templates/game/server_category_selection.html
{%  extends 'base.html' %}
{% load i18n static %}

{% block content %}
    <div class="row">
      <div class="col-lg-12 text-center">
        <h1 class="mt-5">Выберите категорию вопроса. Уровень {{stage_id}}</h1>
      </div>
      {% for category in categories %}
      <div class="col-lg-6 text-center">
        <button class="btn btn-primary btn-lg btn-block mt-5">{{category.name}}</button>
      </div>
      {% endfor %}
    </div>
{% endblock %}

{% block js %}

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Fun Quiz</title>

  <!-- Bootstrap core CSS -->
 <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
    <div class="container">
      <a class="navbar-brand" href="#">Fun Quiz</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Services</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Contact</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Content -->
  <div class="container">
    {% block content %}
    <div class="row">
      <div class="col-lg-12 text-center">
        <h1 class="mt-5">A Bootstrap 4 Starter Template</h1>
        <p class="lead">Complete with pre-defined file paths and responsive navigation!</p>
        <ul class="list-unstyled">
          <li>Bootstrap 4.3.1</li>
          <li>jQuery 3.4.1</li>
        </ul>
      </div>
    </div>
    {% endblock %}
  </div>

  <!-- Bootstrap core JavaScript -->
<script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

{% csrf_token %}
<script type="text/javascript">
// using jQuery
var csrftoken = jQuery("[name=csrfmiddlewaretoken]").val();
function csrfSafeMethod(method) {
    // these HTTP methods do not require CSRF protection
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
}
$.ajaxSetup({
    beforeSend: function(xhr, settings) {
        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
            xhr.setRequestHeader("X-CSRFToken", csrftoken);
        }
    }
});
</script>


{% block js %}
{% endblock %}
</body>

</html>